name: 批量保活进程

on:
  schedule:
    # 使用cron表达式定义任务运行的时间
    # 每8小时运行一次，运行时间为北京时间 00:00、08:00 和 16:00
    - cron: '0 16,0,8 * * *' # 对应 UTC 时间的16:00、00:00 和 08:00
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 安装依赖
        run: |
          sudo apt-get install sshpass
          sudo apt-get install jq

      - name: 登录各个serv00并执行保活脚本
        env:
          HOSTS_JSON: ${{ secrets.HOSTS_JSON }}
          TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
          TELEGRAM_USERID: ${{secrets.TELEGRAM_USERID}}
          WXSENDKEY: ${{secrets.WXSENDKEY}}
          SENDTYPE: ${{secrets.SENDTYPE}}
        run: |
          chmod +x ./revive.sh
          ./revive.sh
