name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 19 * * *' # 每天 UTC 时间 19:00 运行
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync_latest_from_upstream:
    name: 同步上游仓库最新代码
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      # Step 1: 检出目标仓库的代码
      - name: 检出目标仓库代码
        uses: actions/checkout@v3

      # Step 2: 同步上游代码
      - name: 同步上游改动
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: frankiejun/serv00-play
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          git_log_format_args: --pretty=oneline
          git_config_user: GH Action - Upstream Sync
          git_config_email: action@github.com
          git_config_pull_rebase: false
          shallow_since: 1 month ago

      # Step 3: 恢复被覆盖的文件并检查冲突
      - name: 恢复被覆盖的文件
        run: |
          git restore --source=origin/main --staged --worktree .github/workflows/deploy.yml
          git commit -m "恢复 deploy.yml 文件" || echo "没有文件需要恢复"
        continue-on-error: true

      # Step 4: 检查同步是否失败并输出错误信息
      - name: 检查同步错误
        if: failure()
        run: echo "同步失败！请检查日志了解详细信息。"

      # Step 5: 输出同步成功的消息
      - name: 同步成功消息
        if: success()
        run: echo "同步完成！"

      # Step 6: 删除旧的工作流运行记录
      - name: 删除工作流运行
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 2
          keep_minimum_runs: 6
